require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LuceneSearchesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # LuceneSearch. As you add validations to LuceneSearch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LuceneSearchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lucene_searches as @lucene_searches" do
      lucene_search = LuceneSearch.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:lucene_searches)).to eq([lucene_search])
    end
  end

  describe "GET show" do
    it "assigns the requested lucene_search as @lucene_search" do
      lucene_search = LuceneSearch.create! valid_attributes
      get :show, {:id => lucene_search.to_param}, valid_session
      expect(assigns(:lucene_search)).to eq(lucene_search)
    end
  end

  describe "GET new" do
    it "assigns a new lucene_search as @lucene_search" do
      get :new, {}, valid_session
      expect(assigns(:lucene_search)).to be_a_new(LuceneSearch)
    end
  end

  describe "GET edit" do
    it "assigns the requested lucene_search as @lucene_search" do
      lucene_search = LuceneSearch.create! valid_attributes
      get :edit, {:id => lucene_search.to_param}, valid_session
      expect(assigns(:lucene_search)).to eq(lucene_search)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LuceneSearch" do
        expect {
          post :create, {:lucene_search => valid_attributes}, valid_session
        }.to change(LuceneSearch, :count).by(1)
      end

      it "assigns a newly created lucene_search as @lucene_search" do
        post :create, {:lucene_search => valid_attributes}, valid_session
        expect(assigns(:lucene_search)).to be_a(LuceneSearch)
        expect(assigns(:lucene_search)).to be_persisted
      end

      it "redirects to the created lucene_search" do
        post :create, {:lucene_search => valid_attributes}, valid_session
        expect(response).to redirect_to(LuceneSearch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lucene_search as @lucene_search" do
        post :create, {:lucene_search => invalid_attributes}, valid_session
        expect(assigns(:lucene_search)).to be_a_new(LuceneSearch)
      end

      it "re-renders the 'new' template" do
        post :create, {:lucene_search => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lucene_search" do
        lucene_search = LuceneSearch.create! valid_attributes
        put :update, {:id => lucene_search.to_param, :lucene_search => new_attributes}, valid_session
        lucene_search.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested lucene_search as @lucene_search" do
        lucene_search = LuceneSearch.create! valid_attributes
        put :update, {:id => lucene_search.to_param, :lucene_search => valid_attributes}, valid_session
        expect(assigns(:lucene_search)).to eq(lucene_search)
      end

      it "redirects to the lucene_search" do
        lucene_search = LuceneSearch.create! valid_attributes
        put :update, {:id => lucene_search.to_param, :lucene_search => valid_attributes}, valid_session
        expect(response).to redirect_to(lucene_search)
      end
    end

    describe "with invalid params" do
      it "assigns the lucene_search as @lucene_search" do
        lucene_search = LuceneSearch.create! valid_attributes
        put :update, {:id => lucene_search.to_param, :lucene_search => invalid_attributes}, valid_session
        expect(assigns(:lucene_search)).to eq(lucene_search)
      end

      it "re-renders the 'edit' template" do
        lucene_search = LuceneSearch.create! valid_attributes
        put :update, {:id => lucene_search.to_param, :lucene_search => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lucene_search" do
      lucene_search = LuceneSearch.create! valid_attributes
      expect {
        delete :destroy, {:id => lucene_search.to_param}, valid_session
      }.to change(LuceneSearch, :count).by(-1)
    end

    it "redirects to the lucene_searches list" do
      lucene_search = LuceneSearch.create! valid_attributes
      delete :destroy, {:id => lucene_search.to_param}, valid_session
      expect(response).to redirect_to(lucene_searches_url)
    end
  end

end
